[tool.poetry]
name = "aoc"
version = "0.1.0"
description = ""
authors = ["Dmitry Mishanov"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aocd = "^0.1"
ruff = "^0.8.1"
colorama = "^0.4.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
